language: c
dist: trusty
os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - cmake
    - libcunit1-dev

script:
  - gcc --version
  - clang --version
  - cd arduino/surfer/
  - mkdir build_x86
  - cd build_x86
  - cmake ..
  - make -j2
  - ./surfer_test
  - ./surfer_x86

   

