name: CMake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # Or windows-latest, macos-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcunit1-dev

    - uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE

    - name: Configure CMake
      run: |
        cd arduino/surfer
        mkdir build_x86
        cd build_x86
        cmake ..
        make -j2

    - name: Unit test
      run: |
        cd arduino/surfer/build_x86
        ./surfer_test
